version: "3.4"

x-common: &common
  image: locust-tasks:latest
  environment: &common-env
    TARGET_HOST: https://jsonplaceholder.typicode.com
    LOCUSTFILE_PATH: scenarios/random_scenarios.py
    LOCUST_TEST: LoadTests
#  volumes:
#    - ../:/tests

services:

  master:
    <<: *common
    ports:
      - 8089:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master
      EXPECT_SLAVES: 2
      ADD_OPTIONS: "-c 100 -r 20 --no-web"
    networks:
      - loadtest
    hostname: master
    container_name: master

  slave1:
    <<: *common
    links:
      - master
    environment:
      <<: *common-env
      LOCUST_MODE: worker
      LOCUST_MASTER: master
    networks:
      - loadtest
    container_name: slave1

  slave2:
    <<: *common
    links:
      - master
    environment:
      <<: *common-env
      LOCUST_MODE: worker
      LOCUST_MASTER: master
    networks:
      - loadtest
    container_name: slave2

networks:
  loadtest:
    driver: bridge
