version: "3.4"

x-common: &common
  image: locustio/locust
  environment: &common-env
    TARGET_URL: http://locust-master:8089
    LOCUSTFILE_PATH: /tmp/locust-poc/scenarios/basic.py
  volumes:
    - ../:/tests

services:
  locust-master:
    <<: *common
    ports:
      - 8089:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master

  locust-slave:
    <<: *common
    environment:
      <<: *common-env
      LOCUST_MODE: slave
      LOCUST_MASTER_HOST: locust-master



#version: "3.5"
#services:
#  locust-master:
#    image: hakobera/locust:latest
#    environment:
#      - LOCUST_MODE=master
#      - TARGET_URL=https://jsonplaceholder.typicode.com
#      # Other envs
#      - LOCUSTFILE_PATH=/tmp/random_scenarios.py
#      - SCENARIO_FILE=/tmp/random_scenarios.py
#      - LOCUST_MASTER_HOST=locust-master
#    networks:
#      - performance
#    volumes:
#      - ./scenarios:/tmp
#    container_name: locust-master
#  locust-slave1:
#    image: hakobera/locust:latest
#    environment:
#      - LOCUST_MODE=slave
#      - MASTER_HOST=locust-master
#      - TARGET_URL=https://jsonplaceholder.typicode.com
#      # Other envs
#      - LOCUSTFILE_PATH=/tmp/random_scenarios.py
#      - SCENARIO_FILE=/tmp/random_scenarios.py
#      - LOCUST_MASTER_HOST=locust-master
#    networks:
#      - performance
#    volumes:
#      - ./scenarios:/tmp
#    container_name: locust-slave1
#  locust-slave2:
#    image: hakobera/locust:latest
#    environment:
#      - LOCUST_MODE=slave
#      - MASTER_HOST=locust-master
#      - TARGET_URL=https://jsonplaceholder.typicode.com
#      # Other envs
#      - LOCUSTFILE_PATH=/tmp/random_scenarios.py
#      - SCENARIO_FILE=/tmp/random_scenarios.py
#      - LOCUST_MASTER_HOST=locust-master
#    networks:
#      - performance
#    volumes:
#      - ./scenarios:/tmp
#    container_name: locust-slave2
#
#networks:
#  performance:
#    driver: bridge