# ---- Create LOCUST slaves(workers) Deployment----
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: locust-worker
  namespace: locust
  labels:
    name: locust
    role: worker
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust-worker
          image: savvagenchevskiy/locust-tasks:latest
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: https://jsonplaceholder.typicode.com
            - name: LOCUST_TEST
              value: LoadTests
            - name: LOCUSTFILE_PATH
              value: scenarios/random_scenarios.py