execution:
- executor: locust
  concurrency: 15
  ramp-up: 5s
  hold-for:  10s
  scenario: load-tests

scenarios:
  load-tests:
    timeout: 30
    think-time: 1s
    default-address: http://localhost:3000
    keepalive: true
    script: ./locust_scenario.py

reporting:
- module: console
- module: passfail
  criteria:
    - avg-rt >4500ms for 10s, continue as failed
    - avg-rt >5000ms for 5s, stop as failed
    - p99>8000ms for 10s, stop as failed
    - failures >0% for 500ms, stop as failed
    - hits < 5 for 30s, stop as failed